### PR TITLE
modified static files, updated code.html and main.py

### LINKED ISSUE #39: feature: try to detect language from filename for syntax highlighting
Source: https://github.com/pypi/inspector/blob/1ef5cdac3baf7e3ce189bc876a62bcee2c807538/inspector/templates/code.html#L8-L9

When viewing a non-python file via Inspector, like a README.md, the browser highlights the contents incorrectly.

Prism supports a [lot of languages](https://prismjs.com/#supported-languages) and advises on using their [autoloader for languages](https://prismjs.com/#basic-usage-cdn).

### PR DESCRIPTION
**Pull request by saip007**
Fixes #39

### CODE REVIEW

**Comment by saip007** [comment]
hi @di, I made some changes, but unfortunately, the tests are failing. I've reviewed the error messages, but I'm having trouble finding the exact cause.
Would it be possible for you to provide some guidance or insights into why these tests are failing?

**Comment by di** [comment]
Here's the error:

```
Run bin/lint
+ python -m flake8 --max-line-length 88 .
+ python -m black --check inspector/ tests/
would reformat /home/runner/work/inspector/inspector/inspector/main.py

Oh no! 💥 💔 💥
1 file would be reformatted, 5 files would be left unchanged.
Error: Process completed with exit code 1.
```

This means that the autoformatter `black` has determined that the file at `inspector/inspector/inspector/main.py` needs to be reformatted. You can do this by running `make reformat`.

**Comment by saip007** [comment]
thanks @di, you can review the code.
still there would be some edge cases where a python file is saved as ".py, .pyi, .pyc, .pyd, .pyo, .pyw, .pyz." which will be missed now.

**Review by di — APPROVED** [review]
Thanks!

**Pull request merged**
